<?php

/**
 * This file is part of OPUS. The software OPUS has been originally developed
 * at the University of Stuttgart with funding from the German Research Net,
 * the Federal Department of Higher Education and Research and the Ministry
 * of Science, Research and the Arts of the State of Baden-Wuerttemberg.
 *
 * OPUS 4 is a complete rewrite of the original OPUS software and was developed
 * by the Stuttgart University Library, the Library Service Center
 * Baden-Wuerttemberg, the Cooperative Library Network Berlin-Brandenburg,
 * the Saarland University and State Library, the Saxon State Library -
 * Dresden State and University Library, the Bielefeld University Library and
 * the University Library of Hamburg University of Technology with funding from
 * the German Research Foundation and the European Regional Development Fund.
 *
 * LICENCE
 * OPUS is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the Licence, or any later version.
 * OPUS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details. You should have received a copy of the GNU General Public License
 * along with OPUS; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * @copyright   Copyright (c) 2026, OPUS 4 development team
 * @license     http://www.gnu.org/licenses/gpl.html General Public License
 */

namespace Opus\I18n;

use function array_column;
use function array_search;
use function strlen;

/**
 * ISO-639 language codes.
 */
class Languages
{
    /** @var array ISO-639 language codes (part2_b, part2_t, part1, ref_name) */
    private static $languages = [
        'aar' => ['aar', 'aar', 'aa', 'Danakil-Sprache'],
        'abk' => ['abk', 'abk', 'ab', 'Abchasisch'],
        'ace' => ['ace', 'ace', '', 'Aceh-Sprache'],
        'ach' => ['ach', 'ach', '', 'Acholi-Sprache'],
        'ada' => ['ada', 'ada', '', 'Adangme-Sprache'],
        'ady' => ['ady', 'ady', '', 'Adygisch'],
        'afa' => ['afa', 'afa', '', 'Hamitosemitische Sprachen (Andere)'],
        'afh' => ['afh', 'afh', '', 'Afrihili'],
        'afr' => ['afr', 'afr', 'af', 'Afrikaans'],
        'ain' => ['ain', 'ain', '', 'Ainu-Sprache'],
        'aka' => ['aka', 'aka', 'ak', 'Akan-Sprache'],
        'akk' => ['akk', 'akk', '', 'Akkadisch'],
        'alb' => ['alb', 'sqi', 'sq', 'Albanisch'],
        'ale' => ['ale', 'ale', '', 'Aleutisch'],
        'alg' => ['alg', 'alg', '', 'Algonkin-Sprachen (Andere)'],
        'alt' => ['alt', 'alt', '', 'Altaisch'],
        'amh' => ['amh', 'amh', 'am', 'Amharisch'],
        'ang' => ['ang', 'ang', '', 'Altenglisch'],
        'anp' => ['anp', 'anp', '', 'Anga-Sprache'],
        'apa' => ['apa', 'apa', '', 'Apachen-Sprachen'],
        'ara' => ['ara', 'ara', 'ar', 'Arabisch'],
        'arc' => ['arc', 'arc', '', 'Aramäisch'],
        'arg' => ['arg', 'arg', 'an', 'Aragonesisch'],
        'arm' => ['arm', 'hye', 'hy', 'Armenisch'],
        'arn' => ['arn', 'arn', '', 'Arauka-Sprachen'],
        'arp' => ['arp', 'arp', '', 'Arapaho-Sprache'],
        'art' => ['art', 'art', '', 'Kunstsprachen (Andere)'],
        'arw' => ['arw', 'arw', '', 'Arawak-Sprachen'],
        'asm' => ['asm', 'asm', 'as', 'Assamesisch'],
        'ast' => ['ast', 'ast', '', 'Asturisch'],
        'ath' => ['ath', 'ath', '', 'Athapaskische Sprachen (Andere)'],
        'aus' => ['aus', 'aus', '', 'Australische Sprachen'],
        'ava' => ['ava', 'ava', 'av', 'Awarisch'],
        'ave' => ['ave', 'ave', 'ae', 'Avestisch'],
        'awa' => ['awa', 'awa', '', 'Awadhi'],
        'aym' => ['aym', 'aym', 'ay', 'Aymará-Sprache'],
        'aze' => ['aze', 'aze', 'az', 'Aserbeidschanisch'],
        'bad' => ['bad', 'bad', '', 'Banda-Sprachen (Ubangi-Sprachen)'],
        'bai' => ['bai', 'bai', '', 'Bamileke-Sprachen'],
        'bak' => ['bak', 'bak', 'ba', 'Baschkirisch'],
        'bal' => ['bal', 'bal', '', 'Belutschisch'],
        'bam' => ['bam', 'bam', 'bm', 'Bambara-Sprache'],
        'ban' => ['ban', 'ban', '', 'Balinesisch'],
        'baq' => ['baq', 'eus', 'eu', 'Baskisch'],
        'bas' => ['bas', 'bas', '', 'Basaa-Sprache'],
        'bat' => ['bat', 'bat', '', 'Baltische Sprachen (Andere)'],
        'bej' => ['bej', 'bej', '', 'Bedauye'],
        'bel' => ['bel', 'bel', 'be', 'Weißrussisch'],
        'bem' => ['bem', 'bem', '', 'Bemba-Sprache'],
        'ben' => ['ben', 'ben', 'bn', 'Bengali'],
        'ber' => ['ber', 'ber', '', 'Berbersprachen (Andere)'],
        'bho' => ['bho', 'bho', '', 'Bhojpuri'],
        'bih' => ['bih', 'bih', '', 'Bihari (Andere)'],
        'bik' => ['bik', 'bik', '', 'Bikol-Sprache'],
        'bin' => ['bin', 'bin', '', 'Edo-Sprache'],
        'bis' => ['bis', 'bis', 'bi', 'Beach-la-mar'],
        'bla' => ['bla', 'bla', '', 'Blackfoot-Sprache'],
        'bnt' => ['bnt', 'bnt', '', 'Bantusprachen (Andere)'],
        'bos' => ['bos', 'bos', 'bs', 'Bosnisch'],
        'bra' => ['bra', 'bra', '', 'Braj-Bhakha'],
        'bre' => ['bre', 'bre', 'br', 'Bretonisch'],
        'btk' => ['btk', 'btk', '', 'Batak-Sprache'],
        'bua' => ['bua', 'bua', '', 'Burjatisch'],
        'bug' => ['bug', 'bug', '', 'Bugi-Sprache'],
        'bul' => ['bul', 'bul', 'bg', 'Bulgarisch'],
        'bur' => ['bur', 'mya', 'my', 'Birmanisch'],
        'byn' => ['byn', 'byn', '', 'Bilin-Sprache'],
        'cad' => ['cad', 'cad', '', 'Caddo-Sprachen'],
        'cai' => ['cai', 'cai', '', 'Indianersprachen, Zentralamerika (Andere)'],
        'car' => ['car', 'car', '', 'Karibische Sprachen'],
        'cat' => ['cat', 'cat', 'ca', 'Katalanisch'],
        'cau' => ['cau', 'cau', '', 'Kaukasische Sprachen (Andere)'],
        'ceb' => ['ceb', 'ceb', '', 'Cebuano'],
        'cel' => ['cel', 'cel', '', 'Keltische Sprachen (Andere)'],
        'cha' => ['cha', 'cha', 'ch', 'Chamorro-Sprache'],
        'chb' => ['chb', 'chb', '', 'Chibcha-Sprachen'],
        'che' => ['che', 'che', 'ce', 'Tschetschenisch'],
        'chg' => ['chg', 'chg', '', 'Tschagataisch'],
        'chi' => ['chi', 'zho', 'zh', 'Chinesisch'],
        'chk' => ['chk', 'chk', '', 'Trukesisch'],
        'chm' => ['chm', 'chm', '', 'Tscheremissisch'],
        'chn' => ['chn', 'chn', '', 'Chinook-Jargon'],
        'cho' => ['cho', 'cho', '', 'Choctaw-Sprache'],
        'chp' => ['chp', 'chp', '', 'Chipewyan-Sprache'],
        'chr' => ['chr', 'chr', '', 'Cherokee-Sprache'],
        'chu' => ['chu', 'chu', 'cu', 'Kirchenslawisch'],
        'chv' => ['chv', 'chv', 'cv', 'Tschuwaschisch'],
        'chy' => ['chy', 'chy', '', 'Cheyenne-Sprache'],
        'cmc' => ['cmc', 'cmc', '', 'Cham-Sprachen'],
        'cnr' => ['cnr', 'cnr', '', 'Montenegrinisch'],
        'cop' => ['cop', 'cop', '', 'Koptisch'],
        'cor' => ['cor', 'cor', 'kw', 'Kornisch'],
        'cos' => ['cos', 'cos', 'co', 'Korsisch'],
        'cpe' => ['cpe', 'cpe', '', 'Kreolisch-Englisch (Andere)'],
        'cpf' => ['cpf', 'cpf', '', 'Kreolisch-Französisch (Andere)'],
        'cpp' => ['cpp', 'cpp', '', 'Kreolisch-Portugiesisch (Andere)'],
        'cre' => ['cre', 'cre', 'cr', 'Cree-Sprache'],
        'crh' => ['crh', 'crh', '', 'Krimtatarisch'],
        'crp' => ['crp', 'crp', '', 'Kreolische Sprachen; Pidginsprachen (Andere)'],
        'csb' => ['csb', 'csb', '', 'Kaschubisch'],
        'cus' => ['cus', 'cus', '', 'Kuschitische Sprachen (Andere)'],
        'cze' => ['cze', 'ces', 'cs', 'Tschechisch'],
        'dak' => ['dak', 'dak', '', 'Dakota-Sprache'],
        'dan' => ['dan', 'dan', 'da', 'Dänisch'],
        'dar' => ['dar', 'dar', '', 'Darginisch'],
        'day' => ['day', 'day', '', 'Dajakisch'],
        'del' => ['del', 'del', '', 'Delaware-Sprache'],
        'den' => ['den', 'den', '', 'Slave-Sprache'],
        'dgr' => ['dgr', 'dgr', '', 'Tlicho-Sprache; Dogrib-Sprache'],
        'din' => ['din', 'din', '', 'Dinka-Sprache'],
        'div' => ['div', 'div', 'dv', 'Maledivisch'],
        'doi' => ['doi', 'doi', '', 'Dogri'],
        'dra' => ['dra', 'dra', '', 'Drawidische Sprachen (Andere)'],
        'dsb' => ['dsb', 'dsb', '', 'Niedersorbisch'],
        'dua' => ['dua', 'dua', '', 'Duala-Sprachen'],
        'dum' => ['dum', 'dum', '', 'Mittelniederländisch'],
        'dut' => ['dut', 'nld', 'nl', 'Niederländisch'],
        'dyu' => ['dyu', 'dyu', '', 'Dyula-Sprache'],
        'dzo' => ['dzo', 'dzo', 'dz', 'Dzongkha'],
        'efi' => ['efi', 'efi', '', 'Efik'],
        'egy' => ['egy', 'egy', '', 'Ägyptisch'],
        'eka' => ['eka', 'eka', '', 'Ekajuk'],
        'elx' => ['elx', 'elx', '', 'Elamisch'],
        'eng' => ['eng', 'eng', 'en', 'English'],
        'enm' => ['enm', 'enm', '', 'Mittelenglisch'],
        'epo' => ['epo', 'epo', 'eo', 'Esperanto'],
        'est' => ['est', 'est', 'et', 'Estnisch'],
        'ewe' => ['ewe', 'ewe', 'ee', 'Ewe-Sprache'],
        'ewo' => ['ewo', 'ewo', '', 'Ewondo'],
        'fan' => ['fan', 'fan', '', 'Pangwe-Sprache'],
        'fao' => ['fao', 'fao', 'fo', 'Färöisch'],
        'fat' => ['fat', 'fat', '', 'Fante-Sprache'],
        'fij' => ['fij', 'fij', 'fj', 'Fidschi-Sprache'],
        'fil' => ['fil', 'fil', '', 'Pilipino'],
        'fin' => ['fin', 'fin', 'fi', 'Finnisch'],
        'fiu' => ['fiu', 'fiu', '', 'Finnougrische Sprachen (Andere)'],
        'fon' => ['fon', 'fon', '', 'Fon-Sprache'],
        'fre' => ['fre', 'fra', 'fr', 'French'],
        'frm' => ['frm', 'frm', '', 'Mittelfranzösisch'],
        'fro' => ['fro', 'fro', '', 'Altfranzösisch'],
        'frr' => ['frr', 'frr', '', 'Nordfriesisch'],
        'frs' => ['frs', 'frs', '', 'Ostfriesisch'],
        'fry' => ['fry', 'fry', 'fy', 'Friesisch'],
        'ful' => ['ful', 'ful', 'ff', 'Ful'],
        'fur' => ['fur', 'fur', '', 'Friulisch'],
        'gaa' => ['gaa', 'gaa', '', 'Ga-Sprache'],
        'gay' => ['gay', 'gay', '', 'Gayo-Sprache'],
        'gba' => ['gba', 'gba', '', 'Gbaya-Sprache'],
        'gem' => ['gem', 'gem', '', 'Germanische Sprachen (Andere)'],
        'geo' => ['geo', 'kat', 'ka', 'Georgisch'],
        'ger' => ['ger', 'deu', 'de', 'German'],
        'gez' => ['gez', 'gez', '', 'Altäthiopisch'],
        'gil' => ['gil', 'gil', '', 'Gilbertesisch'],
        'gla' => ['gla', 'gla', 'gd', 'Gälisch-Schottisch'],
        'gle' => ['gle', 'gle', 'ga', 'Irisch'],
        'glg' => ['glg', 'glg', 'gl', 'Galicisch'],
        'glv' => ['glv', 'glv', 'gv', 'Manx'],
        'gmh' => ['gmh', 'gmh', '', 'Mittelhochdeutsch'],
        'goh' => ['goh', 'goh', '', 'Althochdeutsch'],
        'gon' => ['gon', 'gon', '', 'Gondi-Sprache'],
        'gor' => ['gor', 'gor', '', 'Gorontalesisch'],
        'got' => ['got', 'got', '', 'Gotisch'],
        'grb' => ['grb', 'grb', '', 'Grebo-Sprache'],
        'grc' => ['grc', 'grc', '', 'Altgriechisch'],
        'gre' => ['gre', 'ell', 'el', 'Neugriechisch'],
        'grn' => ['grn', 'grn', 'gn', 'Guaraní-Sprache'],
        'gsw' => ['gsw', 'gsw', '', 'Schweizerdeutsch'],
        'guj' => ['guj', 'guj', 'gu', 'Gujarati-Sprache'],
        'gwi' => ['gwi', 'gwi', '', 'Kutchin-Sprache'],
        'hai' => ['hai', 'hai', '', 'Haida-Sprache'],
        'hat' => ['hat', 'hat', 'ht', 'Haïtien (Haiti-Kreolisch)'],
        'hau' => ['hau', 'hau', 'ha', 'Haussa-Sprache'],
        'haw' => ['haw', 'haw', '', 'Hawaiisch'],
        'heb' => ['heb', 'heb', 'he', 'Hebräisch'],
        'her' => ['her', 'her', 'hz', 'Herero-Sprache'],
        'hil' => ['hil', 'hil', '', 'Hiligaynon-Sprache'],
        'him' => ['him', 'him', '', 'Himachali'],
        'hin' => ['hin', 'hin', 'hi', 'Hindi'],
        'hit' => ['hit', 'hit', '', 'Hethitisch'],
        'hmn' => ['hmn', 'hmn', '', 'Miao-Sprachen'],
        'hmo' => ['hmo', 'hmo', 'ho', 'Hiri-Motu'],
        'hrv' => ['hrv', 'hrv', 'hr', 'Kroatisch '],
        'hsb' => ['hsb', 'hsb', '', 'Obersorbisch'],
        'hun' => ['hun', 'hun', 'hu', 'Ungarisch'],
        'hup' => ['hup', 'hup', '', 'Hupa-Sprache'],
        'iba' => ['iba', 'iba', '', 'Iban-Sprache'],
        'ibo' => ['ibo', 'ibo', 'ig', 'Ibo-Sprache'],
        'ice' => ['ice', 'isl', 'is', 'Isländisch'],
        'ido' => ['ido', 'ido', 'io', 'Ido'],
        'iii' => ['iii', 'iii', 'ii', 'Lalo-Sprache'],
        'ijo' => ['ijo', 'ijo', '', 'Ijo-Sprache'],
        'iku' => ['iku', 'iku', 'iu', 'Inuktitut'],
        'ile' => ['ile', 'ile', 'ie', 'Interlingue'],
        'ilo' => ['ilo', 'ilo', '', 'Ilokano-Sprache'],
        'ina' => ['ina', 'ina', 'ia', 'Interlingua'],
        'inc' => ['inc', 'inc', '', 'Indoarische Sprachen (Andere)'],
        'ind' => ['ind', 'ind', 'id', 'Bahasa Indonesia'],
        'ine' => ['ine', 'ine', '', 'Indogermanische Sprachen (Andere)'],
        'inh' => ['inh', 'inh', '', 'Inguschisch'],
        'ipk' => ['ipk', 'ipk', 'ik', 'Inupik'],
        'ira' => ['ira', 'ira', '', 'Iranische Sprachen (Andere)'],
        'iro' => ['iro', 'iro', '', 'Irokesische Sprachen'],
        'ita' => ['ita', 'ita', 'it', 'Italian'],
        'jav' => ['jav', 'jav', 'jv', 'Javanisch'],
        'jbo' => ['jbo', 'jbo', '', 'Lojban'],
        'jpn' => ['jpn', 'jpn', 'ja', 'Japanisch'],
        'jpr' => ['jpr', 'jpr', '', 'Jüdisch-Persisch'],
        'jrb' => ['jrb', 'jrb', '', 'Jüdisch-Arabisch'],
        'kaa' => ['kaa', 'kaa', '', 'Karakalpakisch'],
        'kab' => ['kab', 'kab', '', 'Kabylisch'],
        'kac' => ['kac', 'kac', '', 'Kachin-Sprache'],
        'kal' => ['kal', 'kal', 'kl', 'Grönländisch'],
        'kam' => ['kam', 'kam', '', 'Kamba-Sprache'],
        'kan' => ['kan', 'kan', 'kn', 'Kannada'],
        'kar' => ['kar', 'kar', '', 'Karenisch'],
        'kas' => ['kas', 'kas', 'ks', 'Kaschmiri'],
        'kau' => ['kau', 'kau', 'kr', 'Kanuri-Sprache'],
        'kaw' => ['kaw', 'kaw', '', 'Kawi'],
        'kaz' => ['kaz', 'kaz', 'kk', 'Kasachisch'],
        'kbd' => ['kbd', 'kbd', '', 'Kabardinisch'],
        'kha' => ['kha', 'kha', '', 'Khasi-Sprache'],
        'khi' => ['khi', 'khi', '', 'Khoisan-Sprachen (Andere)'],
        'khm' => ['khm', 'khm', 'km', 'Kambodschanisch'],
        'kho' => ['kho', 'kho', '', 'Sakisch'],
        'kik' => ['kik', 'kik', 'ki', 'Kikuyu-Sprache'],
        'kin' => ['kin', 'kin', 'rw', 'Rwanda-Sprache'],
        'kir' => ['kir', 'kir', 'ky', 'Kirgisisch'],
        'kmb' => ['kmb', 'kmb', '', 'Kimbundu-Sprache'],
        'kok' => ['kok', 'kok', '', 'Konkani'],
        'kom' => ['kom', 'kom', 'kv', 'Komi-Sprache'],
        'kon' => ['kon', 'kon', 'kg', 'Kongo-Sprache'],
        'kor' => ['kor', 'kor', 'ko', 'Koreanisch'],
        'kos' => ['kos', 'kos', '', 'Kosraeanisch'],
        'kpe' => ['kpe', 'kpe', '', 'Kpelle-Sprache'],
        'krc' => ['krc', 'krc', '', 'Karatschaiisch-Balkarisch'],
        'krl' => ['krl', 'krl', '', 'Karelisch'],
        'kro' => ['kro', 'kro', '', 'Kru-Sprachen (Andere)'],
        'kru' => ['kru', 'kru', '', 'Oraon-Sprache'],
        'kua' => ['kua', 'kua', 'kj', 'Kwanyama-Sprache'],
        'kum' => ['kum', 'kum', '', 'Kumükisch'],
        'kur' => ['kur', 'kur', 'ku', 'Kurdisch'],
        'kut' => ['kut', 'kut', '', 'Kutenai-Sprache'],
        'lad' => ['lad', 'lad', '', 'Judenspanisch'],
        'lah' => ['lah', 'lah', '', 'Lahnda'],
        'lam' => ['lam', 'lam', '', 'Lamba-Sprache (Bantusprache)'],
        'lao' => ['lao', 'lao', 'lo', 'Laotisch'],
        'lat' => ['lat', 'lat', 'la', 'Latein'],
        'lav' => ['lav', 'lav', 'lv', 'Lettisch'],
        'lez' => ['lez', 'lez', '', 'Lesgisch'],
        'lim' => ['lim', 'lim', 'li', 'Limburgisch'],
        'lin' => ['lin', 'lin', 'ln', 'Lingala'],
        'lit' => ['lit', 'lit', 'lt', 'Litauisch'],
        'lol' => ['lol', 'lol', '', 'Mongo-Sprache'],
        'loz' => ['loz', 'loz', '', 'Rotse-Sprache'],
        'ltz' => ['ltz', 'ltz', 'lb', 'Luxemburgisch'],
        'lua' => ['lua', 'lua', '', 'Lulua-Sprache'],
        'lub' => ['lub', 'lub', 'lu', 'Luba-Katanga-Sprache'],
        'lug' => ['lug', 'lug', 'lg', 'Ganda-Sprache'],
        'lui' => ['lui', 'lui', '', 'Luiseño-Sprache'],
        'lun' => ['lun', 'lun', '', 'Lunda-Sprache'],
        'luo' => ['luo', 'luo', '', 'Luo-Sprache'],
        'lus' => ['lus', 'lus', '', 'Lushai-Sprache'],
        'mac' => ['mac', 'mkd', 'mk', 'Makedonisch'],
        'mad' => ['mad', 'mad', '', 'Maduresisch'],
        'mag' => ['mag', 'mag', '', 'Khotta'],
        'mah' => ['mah', 'mah', 'mh', 'Marschallesisch'],
        'mai' => ['mai', 'mai', '', 'Maithili'],
        'mak' => ['mak', 'mak', '', 'Makassarisch'],
        'mal' => ['mal', 'mal', 'ml', 'Malayalam'],
        'man' => ['man', 'man', '', 'Malinke-Sprache'],
        'mao' => ['mao', 'mri', 'mi', 'Maori-Sprache'],
        'map' => ['map', 'map', '', 'Austronesische Sprachen (Andere)'],
        'mar' => ['mar', 'mar', 'mr', 'Marathi'],
        'mas' => ['mas', 'mas', '', 'Massai-Sprache'],
        'may' => ['may', 'msa', 'ms', 'Malaiisch'],
        'mdf' => ['mdf', 'mdf', '', 'Mokscha-Sprache'],
        'mdr' => ['mdr', 'mdr', '', 'Mandaresisch'],
        'men' => ['men', 'men', '', 'Mende-Sprache'],
        'mga' => ['mga', 'mga', '', 'Mittelirisch'],
        'mic' => ['mic', 'mic', '', 'Micmac-Sprache'],
        'min' => ['min', 'min', '', 'Minangkabau-Sprache'],
        'mis' => ['mis', 'mis', '', 'Einzelne andere Sprachen'],
        'mkh' => ['mkh', 'mkh', '', 'Mon-Khmer-Sprachen (Andere)'],
        'mlg' => ['mlg', 'mlg', 'mg', 'Malagassi-Sprache'],
        'mlt' => ['mlt', 'mlt', 'mt', 'Maltesisch'],
        'mnc' => ['mnc', 'mnc', '', 'Mandschurisch'],
        'mni' => ['mni', 'mni', '', 'Meithei-Sprache'],
        'mno' => ['mno', 'mno', '', 'Manobo-Sprachen'],
        'moh' => ['moh', 'moh', '', 'Mohawk-Sprache'],
        'mon' => ['mon', 'mon', 'mn', 'Mongolisch'],
        'mos' => ['mos', 'mos', '', 'Mossi-Sprache'],
        'mul' => ['mul', 'mul', '', 'Multiple languages'],
        'mun' => ['mun', 'mun', '', 'Mundasprachen (Andere)'],
        'mus' => ['mus', 'mus', '', 'Muskogisch'],
        'mwl' => ['mwl', 'mwl', '', 'Mirandesisch'],
        'mwr' => ['mwr', 'mwr', '', 'Marwari'],
        'myn' => ['myn', 'myn', '', 'Maya-Sprachen'],
        'myv' => ['myv', 'myv', '', 'Erza-Mordwinisch'],
        'nah' => ['nah', 'nah', '', 'Nahuatl'],
        'nai' => ['nai', 'nai', '', 'Indianersprachen, Nordamerika (Andere)'],
        'nap' => ['nap', 'nap', '', 'Neapel / Mundart'],
        'nau' => ['nau', 'nau', 'na', 'Nauruanisch'],
        'nav' => ['nav', 'nav', 'nv', 'Navajo-Sprache'],
        'nbl' => ['nbl', 'nbl', 'nr', 'Ndebele-Sprache (Transvaal)'],
        'nde' => ['nde', 'nde', 'nd', 'Ndebele-Sprache (Simbabwe)'],
        'ndo' => ['ndo', 'ndo', 'ng', 'Ndonga'],
        'nds' => ['nds', 'nds', '', 'Niederdeutsch'],
        'nep' => ['nep', 'nep', 'ne', 'Nepali'],
        'new' => ['new', 'new', '', 'Newari'],
        'nia' => ['nia', 'nia', '', 'Nias-Sprache'],
        'nic' => ['nic', 'nic', '', 'Nigerkordofanische Sprachen (Andere)'],
        'niu' => ['niu', 'niu', '', 'Niue-Sprache'],
        'nno' => ['nno', 'nno', 'nn', 'Nynorsk'],
        'nob' => ['nob', 'nob', 'nb', 'Bokmål'],
        'nog' => ['nog', 'nog', '', 'Nogaisch'],
        'non' => ['non', 'non', '', 'Altnorwegisch'],
        'nor' => ['nor', 'nor', 'no', 'Norwegisch'],
        'nqo' => ['nqo', 'nqo', '', 'N\'Ko'],
        'nso' => ['nso', 'nso', '', 'Pedi-Sprache'],
        'nub' => ['nub', 'nub', '', 'Nubische Sprachen'],
        'nwc' => ['nwc', 'nwc', '', 'Alt-Newari'],
        'nya' => ['nya', 'nya', 'ny', 'Nyanja-Sprache'],
        'nym' => ['nym', 'nym', '', 'Nyamwezi-Sprache'],
        'nyn' => ['nyn', 'nyn', '', 'Nkole-Sprache'],
        'nyo' => ['nyo', 'nyo', '', 'Nyoro-Sprache'],
        'nzi' => ['nzi', 'nzi', '', 'Nzima-Sprache'],
        'oci' => ['oci', 'oci', 'oc', 'Okzitanisch'],
        'oji' => ['oji', 'oji', 'oj', 'Ojibwa-Sprache'],
        'ori' => ['ori', 'ori', 'or', 'Oriya-Sprache'],
        'orm' => ['orm', 'orm', 'om', 'Galla-Sprache'],
        'osa' => ['osa', 'osa', '', 'Osage-Sprache'],
        'oss' => ['oss', 'oss', 'os', 'Ossetisch'],
        'ota' => ['ota', 'ota', '', 'Osmanisch'],
        'oto' => ['oto', 'oto', '', 'Otomangue-Sprachen'],
        'paa' => ['paa', 'paa', '', 'Papuasprachen (Andere)'],
        'pag' => ['pag', 'pag', '', 'Pangasinan-Sprache'],
        'pal' => ['pal', 'pal', '', 'Mittelpersisch'],
        'pam' => ['pam', 'pam', '', 'Pampanggan-Sprache'],
        'pan' => ['pan', 'pan', 'pa', 'Pandschabi-Sprache'],
        'pap' => ['pap', 'pap', '', 'Papiamento'],
        'pau' => ['pau', 'pau', '', 'Palau-Sprache'],
        'peo' => ['peo', 'peo', '', 'Altpersisch'],
        'per' => ['per', 'fas', 'fa', 'Persisch'],
        'phi' => ['phi', 'phi', '', 'Philippinisch-Austronesisch (Andere)'],
        'phn' => ['phn', 'phn', '', 'Phönikisch'],
        'pli' => ['pli', 'pli', 'pi', 'Pali'],
        'pol' => ['pol', 'pol', 'pl', 'Polnisch'],
        'pon' => ['pon', 'pon', '', 'Ponapeanisch'],
        'por' => ['por', 'por', 'pt', 'Portuguese'],
        'pra' => ['pra', 'pra', '', 'Prakrit'],
        'pro' => ['pro', 'pro', '', 'Altokzitanisch'],
        'pus' => ['pus', 'pus', 'ps', 'Paschtu'],
        'que' => ['que', 'que', 'qu', 'Quechua-Sprache'],
        'raj' => ['raj', 'raj', '', 'Rajasthani'],
        'rap' => ['rap', 'rap', '', 'Osterinsel-Sprache'],
        'rar' => ['rar', 'rar', '', 'Rarotonganisch'],
        'roa' => ['roa', 'roa', '', 'Romanische Sprachen (Andere)'],
        'roh' => ['roh', 'roh', 'rm', 'Rätoromanisch'],
        'rom' => ['rom', 'rom', '', 'Romani (Sprache)'],
        'rum' => ['rum', 'ron', 'ro', 'Rumänisch'],
        'run' => ['run', 'run', 'rn', 'Rundi-Sprache'],
        'rup' => ['rup', 'rup', '', 'Aromunisch'],
        'rus' => ['rus', 'rus', 'ru', 'Russian'],
        'sad' => ['sad', 'sad', '', 'Sandawe-Sprache'],
        'sag' => ['sag', 'sag', 'sg', 'Sango-Sprache'],
        'sah' => ['sah', 'sah', '', 'Jakutisch'],
        'sai' => ['sai', 'sai', '', 'Indianersprachen, Südamerika (Andere)'],
        'sal' => ['sal', 'sal', '', 'Salish-Sprache'],
        'sam' => ['sam', 'sam', '', 'Samaritanisch'],
        'san' => ['san', 'san', 'sa', 'Sanskrit'],
        'sas' => ['sas', 'sas', '', 'Sasak'],
        'sat' => ['sat', 'sat', '', 'Santali'],
        'scn' => ['scn', 'scn', '', 'Sizilianisch'],
        'sco' => ['sco', 'sco', '', 'Schottisch'],
        'sel' => ['sel', 'sel', '', 'Selkupisch'],
        'sem' => ['sem', 'sem', '', 'Semitische Sprachen (Andere)'],
        'sga' => ['sga', 'sga', '', 'Altirisch'],
        'sgn' => ['sgn', 'sgn', '', 'Zeichensprachen'],
        'shn' => ['shn', 'shn', '', 'Schan-Sprache'],
        'sid' => ['sid', 'sid', '', 'Sidamo-Sprache'],
        'sin' => ['sin', 'sin', 'si', 'Singhalesisch'],
        'sio' => ['sio', 'sio', '', 'Sioux-Sprachen (Andere)'],
        'sit' => ['sit', 'sit', '', 'Sinotibetische Sprachen (Andere)'],
        'sla' => ['sla', 'sla', '', 'Slawische Sprachen (Andere)'],
        'slo' => ['slo', 'slk', 'sk', 'Slowakisch'],
        'slv' => ['slv', 'slv', 'sl', 'Slowenisch'],
        'sma' => ['sma', 'sma', '', 'Südsaamisch'],
        'sme' => ['sme', 'sme', 'se', 'Nordsaamisch'],
        'smi' => ['smi', 'smi', '', 'Saamisch'],
        'smj' => ['smj', 'smj', '', 'Lulesaamisch'],
        'smn' => ['smn', 'smn', '', 'Inarisaamisch'],
        'smo' => ['smo', 'smo', 'sm', 'Samoanisch'],
        'sms' => ['sms', 'sms', '', 'Skoltsaamisch'],
        'sna' => ['sna', 'sna', 'sn', 'Schona-Sprache'],
        'snd' => ['snd', 'snd', 'sd', 'Sindhi-Sprache'],
        'snk' => ['snk', 'snk', '', 'Soninke-Sprache'],
        'sog' => ['sog', 'sog', '', 'Sogdisch'],
        'som' => ['som', 'som', 'so', 'Somali'],
        'son' => ['son', 'son', '', 'Songhai-Sprache'],
        'sot' => ['sot', 'sot', 'st', 'Süd-Sotho-Sprache'],
        'spa' => ['spa', 'spa', 'es', 'Spanish'],
        'srd' => ['srd', 'srd', 'sc', 'Sardisch'],
        'srn' => ['srn', 'srn', '', 'Sranantongo'],
        'srp' => ['srp', 'srp', 'sr', 'Serbisch '],
        'srr' => ['srr', 'srr', '', 'Serer-Sprache'],
        'ssa' => ['ssa', 'ssa', '', 'Nilosaharanische Sprachen (Andere)'],
        'ssw' => ['ssw', 'ssw', 'ss', 'Swasi-Sprache'],
        'suk' => ['suk', 'suk', '', 'Sukuma-Sprache'],
        'sun' => ['sun', 'sun', 'su', 'Sundanesisch'],
        'sus' => ['sus', 'sus', '', 'Susu'],
        'sux' => ['sux', 'sux', '', 'Sumerisch'],
        'swa' => ['swa', 'swa', 'sw', 'Swahili'],
        'swe' => ['swe', 'swe', 'sv', 'Schwedisch'],
        'syc' => ['syc', 'syc', '', 'Syrisch'],
        'syr' => ['syr', 'syr', '', 'Neuostaramäisch'],
        'tah' => ['tah', 'tah', 'ty', 'Tahitisch'],
        'tai' => ['tai', 'tai', '', 'Thaisprachen (Andere)'],
        'tam' => ['tam', 'tam', 'ta', 'Tamil'],
        'tat' => ['tat', 'tat', 'tt', 'Tatarisch'],
        'tel' => ['tel', 'tel', 'te', 'Telugu-Sprache'],
        'tem' => ['tem', 'tem', '', 'Temne-Sprache'],
        'ter' => ['ter', 'ter', '', 'Tereno-Sprache'],
        'tet' => ['tet', 'tet', '', 'Tetum-Sprache'],
        'tgk' => ['tgk', 'tgk', 'tg', 'Tadschikisch'],
        'tgl' => ['tgl', 'tgl', 'tl', 'Tagalog'],
        'tha' => ['tha', 'tha', 'th', 'Thailändisch'],
        'tib' => ['tib', 'bod', 'bo', 'Tibetisch'],
        'tig' => ['tig', 'tig', '', 'Tigre-Sprache'],
        'tir' => ['tir', 'tir', 'ti', 'Tigrinja-Sprache'],
        'tiv' => ['tiv', 'tiv', '', 'Tiv-Sprache'],
        'tkl' => ['tkl', 'tkl', '', 'Tokelauanisch'],
        'tlh' => ['tlh', 'tlh', '', 'Klingonisch'],
        'tli' => ['tli', 'tli', '', 'Tlingit-Sprache'],
        'tmh' => ['tmh', 'tmh', '', 'Tamašeq'],
        'tog' => ['tog', 'tog', '', 'Tonga (Bantusprache, Sambia)'],
        'ton' => ['ton', 'ton', 'to', 'Tongaisch'],
        'tpi' => ['tpi', 'tpi', '', 'Neumelanesisch'],
        'tsi' => ['tsi', 'tsi', '', 'Tsimshian-Sprache'],
        'tsn' => ['tsn', 'tsn', 'tn', 'Tswana-Sprache'],
        'tso' => ['tso', 'tso', 'ts', 'Tsonga-Sprache'],
        'tuk' => ['tuk', 'tuk', 'tk', 'Turkmenisch'],
        'tum' => ['tum', 'tum', '', 'Tumbuka-Sprache'],
        'tup' => ['tup', 'tup', '', 'Tupi-Sprache'],
        'tur' => ['tur', 'tur', 'tr', 'Türkisch'],
        'tut' => ['tut', 'tut', '', 'Altaische Sprachen (Andere)'],
        'tvl' => ['tvl', 'tvl', '', 'Elliceanisch'],
        'twi' => ['twi', 'twi', 'tw', 'Twi-Sprache'],
        'tyv' => ['tyv', 'tyv', '', 'Tuwinisch'],
        'udm' => ['udm', 'udm', '', 'Udmurtisch'],
        'uga' => ['uga', 'uga', '', 'Ugaritisch'],
        'uig' => ['uig', 'uig', 'ug', 'Uigurisch'],
        'ukr' => ['ukr', 'ukr', 'uk', 'Ukrainisch'],
        'umb' => ['umb', 'umb', '', 'Mbundu-Sprache'],
        'urd' => ['urd', 'urd', 'ur', 'Urdu'],
        'uzb' => ['uzb', 'uzb', 'uz', 'Usbekisch'],
        'vai' => ['vai', 'vai', '', 'Vai-Sprache'],
        'ven' => ['ven', 'ven', 've', 'Venda-Sprache'],
        'vie' => ['vie', 'vie', 'vi', 'Vietnamesisch'],
        'vol' => ['vol', 'vol', 'vo', 'Volapük'],
        'vot' => ['vot', 'vot', '', 'Wotisch'],
        'wak' => ['wak', 'wak', '', 'Wakash-Sprachen'],
        'wal' => ['wal', 'wal', '', 'Walamo-Sprache'],
        'war' => ['war', 'war', '', 'Waray'],
        'was' => ['was', 'was', '', 'Washo-Sprache'],
        'wel' => ['wel', 'cym', 'cy', 'Kymrisch'],
        'wen' => ['wen', 'wen', '', 'Sorbisch (Andere)'],
        'wln' => ['wln', 'wln', 'wa', 'Wallonisch'],
        'wol' => ['wol', 'wol', 'wo', 'Wolof-Sprache'],
        'xal' => ['xal', 'xal', '', 'Kalmückisch'],
        'xho' => ['xho', 'xho', 'xh', 'Xhosa-Sprache'],
        'yao' => ['yao', 'yao', '', 'Yao-Sprache (Bantusprache)'],
        'yap' => ['yap', 'yap', '', 'Yapesisch'],
        'yid' => ['yid', 'yid', 'yi', 'Jiddisch'],
        'yor' => ['yor', 'yor', 'yo', 'Yoruba-Sprache'],
        'ypk' => ['ypk', 'ypk', '', 'Ypik-Sprachen'],
        'zap' => ['zap', 'zap', '', 'Zapotekisch'],
        'zbl' => ['zbl', 'zbl', '', 'Bliss-Symbol'],
        'zen' => ['zen', 'zen', '', 'Zenaga'],
        'zgh' => ['zgh', 'zgh', '', 'Marokkanisches Tamazight'],
        'zha' => ['zha', 'zha', 'za', 'Zhuang'],
        'znd' => ['znd', 'znd', '', 'Zande-Sprachen'],
        'zul' => ['zul', 'zul', 'zu', 'Zulu-Sprache'],
        'zun' => ['zun', 'zun', '', 'Zuñi-Sprache'],
        'zxx' => ['zxx', 'zxx', '', 'Keine Angabe'],
        'zza' => ['zza', 'zza', '', 'Zazaki'],
    ];

    public function getAllAsArray(): array
    {
        return self::$languages;
    }

    public static function getLanguage(string $code): ?Language
    {
        if (strlen($code) === 2) {
            return self::getLanguageByPart1($code);
        }

        $language = self::getLanguageByPart2b($code);

        if ($language !== null) {
            return $language;
        }

        return self::getLanguageByPart2t($code);
    }

    public static function getLanguageByPart2b(string $code): ?Language
    {
        $language = self::$languages[$code] ?? null;
        return $language !== null ? new Language($language) : null;
    }

    public static function getLanguageByPart1(string $code): ?Language
    {
        $index = array_search($code, array_column(self::$languages, 2, 0));
        return $index !== false ? new Language(self::$languages[$index]) : null;
    }

    public static function getLanguageByPart2t(string $code): ?Language
    {
        $index = array_search($code, array_column(self::$languages, 1, 0));
        return $index !== false ? new Language(self::$languages[$index]) : null;
    }

    public static function getPart1(?string $code, ?string $default = null): ?string
    {
        if ($code === null) {
            return $default;
        }
        $language = self::getLanguage($code);
        return $language !== null ? $language->getPart1() : $default;
    }

    public static function getPart2b(?string $code, ?string $default = null): ?string
    {
        if ($code === null) {
            return $default;
        }
        $language = self::getLanguage($code);
        return $language !== null ? $language->getPart2b() : $default;
    }

    public static function getPart2t(?string $code, ?string $default = null): ?string
    {
        if ($code === null) {
            return $default;
        }
        $language = self::getLanguage($code);
        return $language !== null ? $language->getPart2t() : $default;
    }
}
